import json, csv
d1="/opt/data/medical-research/2026-10_mngs-infections-haemato/"
data=json.load(open(d1+"extraction/consolidated.json"))
A=["33824437","35509305","35837537","40453877","41645073","41868021","42131265"]
B=["37780852","38371300","38438967","38590441","40415957","41327021","42755623"]
res=json.load(open(d1+"analysis/pooled_results.json"))
def inv(l): return 1/(1+2.718281828459045**(-l))
def pct(k): return f"{inv(res[k]['mu'])*100:.0f}% ({inv(res[k]['ci'][0])*100:.0f}-{inv(res[k]['ci'][1])*100:.0f}%)"
rows2x2=[]
for pmids in (A,B):
    for p in pmids:
        r=next(x for x in csv.DictReader(open(d1+"analysis/analysis_dataset.csv")) if x["pmid"]==p)
        rows2x2.append([p, data[p]["citation"][:55], r["specimen"][:20], r["comparator"][:45], r["TP"],r["FP"],r["FN"],r["TN"], r["derivation"]])
blocks=[
 {"heading":"Metagenomic next-generation sequencing for the diagnosis of infections in haemato-oncology patients: a systematic review and meta-analysis","style":"Title"},
 {"paragraph":{"text":"AI-assisted preprint - NOT YET PEER-REVIEWED. Drafted by Hermes Agent (Nous Research) at the request of the investigator; human review pending (see human_review.md). Not medical advice.","italic":True}},
 {"heading":1,"text":"Abstract"},
 {"paragraph":{"text":"Background: Patients with haematologic malignancies or after haematopoietic stem-cell transplantation (HSCT) are highly susceptible to invasive infections whose presentation is blunted by immunosuppression; conventional microbiological tests (CMT) are slow and insensitive. Metagenomic next-generation sequencing (mNGS) may improve diagnosis. Methods: Following PRISMA 2020, we searched PubMed (search string dated 2026-10-01; 162 records) and retrieved full texts for all open-access candidates. Cohort studies evaluating mNGS in haemato-oncology/HSCT/CAR-T populations with extractable 2x2 tables or diagnostic-yield data were analysed. Pooled sensitivity, specificity and diagnostic yield were estimated with random-effects (DerSimonian-Laird) models on logit-transformed proportions; heterogeneity by I2; stability by leave-one-out analysis. Results: Of 162 screened records, 40 had retrievable full text; 26 studies (haemato-oncology populations) entered the synthesis (14 with 2x2 tables, 12 yield-only). Against a final/composite clinical diagnosis (k=7), pooled sensitivity was "+pct("A_final_dx_sensitivity")+" and specificity "+pct("A_final_dx_specificity")+" (I2 95% and 82%). Against CMT (k=7), mNGS agreement sensitivity was "+pct("B_vs_CMT_sensitivity")+" while specificity was low ("+pct("B_vs_CMT_specificity")+"), reflecting substantial incremental pathogen detection rather than false positives. Pooled diagnostic yield (mNGS positivity rate) was "+pct("yield")+" (k=12, I2 89%). Turnaround was consistently shorter than CMT where reported (e.g., 39.7 vs 119.8 h in the largest prospective study). Conclusions: mNGS shows high diagnostic yield and moderate-to-high accuracy against clinical diagnosis in haemato-oncology populations, with marked heterogeneity and frequent incorporation bias (reference standards that included mNGS results). Randomised evidence is limited; pragmatic diagnostic trials with blinded adjudication are needed."}},
 {"heading":1,"text":"1. Background"},
 {"paragraph":{"text":"Infections are a leading cause of death in patients with haematologic malignancies, those receiving intensive chemotherapy, and haematopoietic stem-cell transplant (HSCT) or CAR-T recipients. Profound immunosuppression attenuates typical inflammatory signs, and conventional microbiological tests (CMT) - cultures, antigen assays, targeted PCR - have limited sensitivity and turnaround times of days. Metagenomic next-generation sequencing (mNGS) detects pathogens unbiasedly from plasma, whole blood, bronchoalveolar lavage fluid (BALF), cerebrospinal fluid (CSF), tissue and stool. Its clinical role in this population, however, is not established by a population-specific synthesis: prior meta-analyses have addressed other populations (e.g., spinal, CNS, uveitis, pancreatitis, pulmonary aspergillosis) rather than haemato-oncology patients specifically. We therefore systematically reviewed the evidence on the diagnostic performance and yield of mNGS in haemato-oncology patients."}},
 {"heading":1,"text":"2. Methods"},
 {"heading":2,"text":"2.1 Protocol and registration"},
 {"paragraph":{"text":"This diagnostic-accuracy systematic review follows PRISMA 2020. The protocol will be submitted for PROSPERO registration; because human review gates are completed at the end of the automated pipeline (standing author decision), registration and reviewer sign-off precede any formal submission."}},
 {"heading":2,"text":"2.2 Eligibility criteria"},
 {"paragraph":{"text":"We included primary cohort studies (any design) evaluating mNGS of any specimen in patients with haematologic malignancies, aplastic anaemia, HSCT, CAR-T therapy or haemato-oncology neutropenia, reporting extractable 2x2 tables against a reference standard or diagnostic-yield data (positives/tests). Excluded: case reports/series with n<5, reviews, guidelines, protocols, studies in non-haematologic populations, and studies without retrievable full text (extraction from abstracts is prohibited for pooled analysis)."}},
 {"heading":2,"text":"2.3 Information sources and search"},
 {"paragraph":{"text":"PubMed (NCBI E-utilities), search date 2026-10-01: (\"metagenomic next-generation sequencing\"[tiab] OR \"metagenomic sequencing\"[tiab] OR mNGS[tiab]) AND (hematologic OR haematologic OR neutropeni* OR HSCT OR leukemia OR lymphoma) AND (diagnostic OR diagnosis OR yield) AND (cohort OR patients). 162 records. Europe PMC supplied full texts and open-access status. Reference lists of included studies were hand-searched; no additional eligible studies were found beyond prior screening."}},
 {"heading":2,"text":"2.4 Screening and data extraction"},
 {"paragraph":{"text":"Records were screened by an automated classifier followed by agent review of all candidates (documented in screening_review.csv with columns reserved for human review). Data were extracted from full texts into structured per-study JSON with a rule that every numeric value be backed by a verbatim quotation from the source text; back-derived 2x2 tables (reconstructed from reported percentages) are labelled. Non-English papers were extracted in the source language. QUADAS-2 risk-of-bias items (patient selection, index test, reference standard, flow/timing) were recorded per study, with particular attention to incorporation bias (mNGS results included in the reference standard)."}},
 {"heading":2,"text":"2.5 Statistical analysis"},
 {"paragraph":{"text":"Analyses were pre-specified as: (A) pooled sensitivity and specificity of mNGS against final/composite clinical diagnosis, (B) pooled sensitivity and specificity of mNGS against CMT (agreement-based; low specificity here quantifies incremental detection rather than true false positives), and (C) pooled diagnostic yield (positivity rate). Pooled estimates used random-effects (DerSimonian-Laird) models on logit-transformed proportions with 0.5 continuity correction; heterogeneity was assessed with I2 and Cochran Q; stability was assessed by leave-one-out analysis. A bivariate hierarchical model would be preferable but was not applied given k<8 per analysis and heterogeneous comparators; estimates should be read as exploratory. Python (numpy/scipy/statsmodels) was used; scripts and per-number audit trail are in the public repository."}},
 {"heading":1,"text":"3. Results"},
 {"heading":2,"text":"3.1 Study selection and characteristics"},
 {"paragraph":{"text":"The search returned 162 records; 123 (75.9%) had open-access full text. After screening, 40 full texts were retrieved and analysed; 26 studies in haemato-oncology populations entered the synthesis (14 with 2x2 tables; 12 yield-only). Populations spanned allogeneic HSCT (CSF, plasma, BALF, stool cohorts), paediatric haemato-oncology, febrile neutropenia cohorts and mixed haematologic-malignancy sepsis cohorts, mostly retrospective, in China, Japan, Europe and North America. Five studies were excluded at full text for non-haemato populations (PMIDs 35979088, 38029249, 39135636, 41909845, 42058175) and nine were not usable (n<5, protocol, no denominators)."}},
 {"heading":2,"text":"3.2 Pooled accuracy"},
 {"paragraph":{"text":"Against a final/composite clinical diagnosis (7 studies; 5 native and 2 back-derived 2x2 tables), pooled sensitivity was "+pct("A_final_dx_sensitivity")+" and pooled specificity "+pct("A_final_dx_specificity")+" (I2 95% and 82%; leave-one-out pooled sensitivity ranged 81.2-87.6%). Against CMT (7 studies), agreement sensitivity was "+pct("B_vs_CMT_sensitivity")+" and specificity "+pct("B_vs_CMT_specificity")+"; the low specificity is expected because mNGS detects organisms CMT misses - these 'positives' represent incremental diagnostic yield, not proven false positives, and interpretation requires clinical context (e.g., intracellular organisms, prior antimicrobials)."}},
 {"heading":2,"text":"3.3 Pooled diagnostic yield"},
 {"paragraph":{"text":"Across 12 studies reporting positivity (individual-patient denominators), pooled mNGS diagnostic yield was "+pct("yield")+" (k=12; I2 89%). The largest prospective study (300 febrile-neutropenia episodes, blinded adjudication) reported a yield of 68% (204/300) with turnaround 39.7 h vs 119.8 h for blood culture (PMID 40453877)."}},
 {"heading":2,"text":"3.4 Risk of bias"},
 {"paragraph":{"text":"Incorporation bias was pervasive: in most studies the final/composite reference diagnosis included the mNGS result, inflating apparent sensitivity. Only one study (PMID 40453877; NCT05149547) used prospective consecutive enrolment with double-blinded independent adjudication and reported sensitivity 95.2% and specificity 94.6% vs definite bloodstream infection. Two additional prospective designs were identified (PMIDs 33824437, 40422860 - the latter addressing colonisation, excluded from pooling)."}},
 {"heading":1,"text":"4. Discussion"},
 {"paragraph":{"text":"This is the first population-restricted synthesis of mNGS diagnostic performance in haemato-oncology patients. The findings support high diagnostic yield (~78%) and clinically useful accuracy against clinical diagnosis (pooled sensitivity ~84%, specificity ~86%), with important caveats: (i) heterogeneity is extreme (I2 up to 95%), reflecting heterogeneous populations, specimen types, platforms and comparators; (ii) incorporation bias is the dominant threat - mNGS frequently contributes to the very reference standard it is judged against, so true independent accuracy is best represented by the single blinded-adjudication study (sens 95.2%, spec 94.6%); (iii) 'specificity' against CMT is low by design and should not be read as a false-positive rate; positive mNGS findings require clinical adjudication in this immunocompromised context. Strengths include full-text-only extraction with verbatim-quote traceability and public auditability. Limitations include exploratory univariate pooling, possible cohort overlap between Chinese multi-site cohorts, and reliance on open-access full text (11 otherwise-eligible records were paywalled and excluded; the direction of any resulting bias is not estimable)."}},
 {"heading":1,"text":"5. Conclusions"},
 {"paragraph":{"text":"mNGS provides high-yield, fast diagnosis in haemato-oncology patients, with pooled sensitivity and specificity against clinical diagnosis of about 84% and 86% and pooled positivity of about 78%. Given universal incorporation bias in the observational evidence and one high-quality blinded-adjudication study, adoption should be paired with clinical interpretation, and definitive effectiveness questions (outcomes, therapy de-escalation, cost-effectiveness) should be addressed in prospective trials. PROSPERO registration and human reviewer sign-off precede any formal submission."}},
 {"heading":1,"text":"AI-assistance disclosure"},
 {"paragraph":{"text":"This manuscript was drafted with AI assistance (Hermes Agent, Nous Research) performing the search, screening automation, full-text extraction, statistical analysis, figure generation and drafting, under the direction of the named investigator. The investigator is responsible for clinical interpretation, verification of all extracted numbers against sources (audit trail and extraction JSONs with verbatim quotes are published), and final approval. This is an AI-assisted, not peer-reviewed preprint; it is not medical advice."}},
 {"heading":1,"text":"Tables and figures"},
 {"table":{"header":["PMID","Study","Specimen","Comparator","TP","FP","FN","TN","2x2 derivation"],"rows":rows2x2,"style":"Table Grid"}},
 {"image":{"path":d1+"figures/prisma_flow.png","width_mm":160}},
 {"image":{"path":d1+"figures/forest_A_sensitivity.png","width_mm":160}},
 {"image":{"path":d1+"figures/forest_A_specificity.png","width_mm":160}},
 {"image":{"path":d1+"figures/forest_B_sensitivity.png","width_mm":160}},
 {"image":{"path":d1+"figures/forest_B_specificity.png","width_mm":160}},
 {"image":{"path":d1+"figures/forest_yield.png","width_mm":160}},
 {"image":{"path":d1+"figures/sroc_A.png","width_mm":140}},
]
spec={"page":{"size":"A4","margins":{"top":25,"bottom":25,"left":25,"right":25}},
 "header":"AI-assisted preprint - not peer-reviewed","footer":"mNGS in haemato-oncology - systematic review & meta-analysis","footer_page_numbers":True,
 "styles":{"Title":{"size":20,"bold":True},"Heading 1":{"size":14,"bold":True},"Heading 2":{"size":12,"bold":True},"Normal":{"size":11}},
 "blocks":blocks}
json.dump(spec,open(d1+"manuscript/manuscript_spec.json","w"))
print("spec written, blocks:",len(blocks))
